name: Auto Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [8.3]
        laravel: [11.*]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, dom, filter, gd, iconv, json, mbstring, pdo, phar, tokenizer, xml, xmlwriter, zip
          coverage: none

      - name: Install dependencies
        uses: ramsey/composer-install@v2
        with:
          composer-options: --prefer-dist --optimize-autoloader

      - name: Run tests
        run: vendor/bin/phpunit

  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, dom, filter, gd, iconv, json, mbstring, pdo, phar, tokenizer, xml, xmlwriter, zip
          coverage: none

      - name: Install dependencies
        uses: ramsey/composer-install@v2
        with:
          composer-options: --prefer-dist --optimize-autoloader

      - name: Run security check
        run: composer audit --format=json --no-interaction

  release:
    needs: [test, security]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, dom, filter, gd, iconv, json, mbstring, pdo, phar, tokenizer, xml, xmlwriter, zip
          coverage: none

      - name: Install Composer
        uses: ramsey/composer-install@v2
        with:
          composer-options: --no-dev --optimize-autoloader

      - name: Get current version
        id: current_version
        run: |
          # Read version directly from composer.json with better error handling
          if [ -f composer.json ]; then
            CURRENT_VERSION=$(grep '"version"' composer.json | sed 's/.*"version": "\([^"]*\)".*/\1/' | tr -d ' ')
            if [ -z "$CURRENT_VERSION" ] || [ "$CURRENT_VERSION" = "null" ]; then
              echo "No version found in composer.json, using default"
              CURRENT_VERSION="0.1.0"
            fi
          else
            echo "composer.json not found, using default version"
            CURRENT_VERSION="0.1.0"
          fi
          echo "current_version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
          echo "Current version: $CURRENT_VERSION"

      - name: Calculate new version
        id: new_version
        run: |
          CURRENT_VERSION="${{ steps.current_version.outputs.current_version }}"
          echo "Processing version: $CURRENT_VERSION"

          # Split version into parts
          IFS='.' read -ra VERSION_PARTS <<< "$CURRENT_VERSION"

          if [ ${#VERSION_PARTS[@]} -ne 3 ]; then
            echo "Invalid version format, using default"
            NEW_VERSION="0.1.0"
          else
            MAJOR=${VERSION_PARTS[0]}
            MINOR=${VERSION_PARTS[1]}
            PATCH=${VERSION_PARTS[2]}

            # Validate parts are numbers
            if ! [[ "$MAJOR" =~ ^[0-9]+$ ]] || ! [[ "$MINOR" =~ ^[0-9]+$ ]] || ! [[ "$PATCH" =~ ^[0-9]+$ ]]; then
              echo "Invalid version numbers, using default"
              NEW_VERSION="0.1.0"
            else
              # Auto-increment patch version
              NEW_PATCH=$((PATCH + 1))
              NEW_VERSION="$MAJOR.$MINOR.$NEW_PATCH"
            fi
          fi

          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
          echo "New version: $NEW_VERSION"

      - name: Update composer.json version
        run: |
          composer config version ${{ steps.new_version.outputs.new_version }}
          echo "Updated composer.json version to ${{ steps.new_version.outputs.new_version }}"

      - name: Commit and push version update
        run: |
          git add composer.json
          git commit -m "Bump version to ${{ steps.new_version.outputs.new_version }}"
          git push

      - name: Check if tag exists
        id: tag_check
        run: |
          TAG_NAME="v${{ steps.new_version.outputs.new_version }}"
          if git tag -l "$TAG_NAME" | grep -q "$TAG_NAME"; then
            echo "tag_exists=true" >> $GITHUB_OUTPUT
            echo "Tag $TAG_NAME already exists"
          else
            echo "tag_exists=false" >> $GITHUB_OUTPUT
            echo "Tag $TAG_NAME does not exist"
          fi

      - name: Create and push tag
        if: steps.tag_check.outputs.tag_exists == 'false'
        run: |
          git tag -a "v${{ steps.new_version.outputs.new_version }}" -m "Release ${{ steps.new_version.outputs.new_version }}"
          git push origin "v${{ steps.new_version.outputs.new_version }}"

      - name: Create GitHub Release
        if: steps.tag_check.outputs.tag_exists == 'false'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.new_version.outputs.new_version }}
          release_name: Release ${{ steps.new_version.outputs.new_version }}
          body: |
            ## Release ${{ steps.new_version.outputs.new_version }}

            ### What's Changed
            - Automated release via GitHub Actions
            - Version calculated: ${{ steps.new_version.outputs.new_version }}

            ### Installation
            ```bash
            composer require fullstack/redbird:${{ steps.new_version.outputs.new_version }}
            ```

            ### Changelog
            This release includes all changes since the last release.

            **Note:** This is an automated release. For detailed changelog, please check the commit history.
          draft: false
          prerelease: false

      - name: Notify Packagist
        run: |
          echo "Release v${{ steps.new_version.outputs.new_version }} created successfully!"
          echo "Packagist will automatically update if webhook is configured."
          echo "Package URL: https://packagist.org/packages/fullstack/redbird"

      - name: Skip release if tag exists
        if: steps.tag_check.outputs.tag_exists == 'true'
        run: |
          echo "Tag v${{ steps.new_version.outputs.new_version }} already exists, skipping release creation"
          echo "This usually means the release was already created in a previous run"
